---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- include: influxdb.yml
  tags: influxdb_schema

- include: mysql.yml
  tags: mysql_schema

- include: kafka_topics.yml
  tags: kafka_topics

