---
# ©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Create database root dir
  file:
    path: "{{ monasca_sql_basedir }}"
    state: directory
    mode: 0755
    recurse: yes

- name: Copy mysql schema to host
  template:
    dest: "{{ monasca_schema_file }}"
    owner: root
    group: root
    mode: 0640
    src: mon_mysql.sql.j2
  register: copy_result

- name: Create monasca database and apply dump to it
  mysql_db:
    login_host: "{{ monasca_mysql_host }}"
    login_user: "{{ monasca_mysql_admin }}"
    login_password: "{{ monasca_mysql_admin_password }}"
    name: "{{ monasca_mysql_db }}"
    state: import
    target: "{{ monasca_schema_file }}"
