---
- name: Copy mysql schema to host
  template: dest={{monasca_schema_file}} owner=root group=root mode=640 src=mon.sql.j2
  register: copy_result

- name: Apply mysql schema to db
  shell: mysql -u{{mysql_admin}} -p{{mysql_admin_password}} < {{monasca_schema_file}}
  when: copy_result|changed

