---
- name: Copy over vertica sql files
  copy: src={{ item }} dest=/var/vertica/{{ item }} mode=660
  with_items:
    - mon_alarms_schema.sql
    - mon_grants.sql
    - mon_metrics_schema.sql
  register: sql_file_status

- name: Copy over template vertica sql files
  template: src={{ item }}.j2 dest=/var/vertica/{{ item }} mode=660
  with_items:
    - mon_schema.sql
    - mon_users.sql
  register: sql_template_status 

- name: Write schema to vertica
  shell: /opt/vertica/bin/vsql -U dbadmin -w  {{vertica_dbadmin_password}} < /var/vertica/{{ item }}
  with_items:
    - mon_schema.sql
    - mon_metrics_schema.sql
    - mon_alarms_schema.sql
    - mon_users.sql
    - mon_grants.sql
  when: sql_file_status|changed or sql_template_status|changed
  
